global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'golang-services'
    scrape_interval: 5s
    static_configs:
      - targets: ['order-service:8080']
        labels:
          service: 'order-service'
          env: 'development'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

rule_files:
  - 'alert.rules.yml'