// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"time"
)

// Injectors from wire.go:

// InitializeGreeter creates a Greeter instance with all dependencies injected
func InitializeGreeter() Greeter {
	timeTime := time.Now()
	message := GetCurrentTimeMessage(timeTime)
	greeter := NewGreeter(message)
	return greeter
}
