// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InintApp(db map[int]any) *App {
	repository := NewRepository(db)
	service := NewService(repository)
	app := NewApp(repository, service)
	return app
}
